# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483df08c122d529081b0cad3059ac7e6d62edee86437a95e795bd116e152a03d1641ccaa07bd083f184d06984145378a0e85be752e84734e6e8f172bf2bf59b0

test:
  secret_key_base: 221a7c2e854db52afba7da1ae6fc2899cbe606acdde0e3b02554684aea0859e7e735df108ab188e59294da39393106dea3a8ae9595d93aef0fa69511605b4b45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
